name: Filippo Teodoro
favicon: null
layout_spectrum: 0.2594
typography_spectrum: 0.49875
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62290697-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#5F83BD'
    - '#FFFFFF'
    - '#213D59'
    - '#BBBDC8'
  brandStrength: 0.5042553
  lightness: 0.7234042
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
