name: Filippo Teodoro
favicon: null
layout_spectrum: 0.2594
typography_spectrum: 0.49875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62290697-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85d0f0'
    - '#ffffff'
    - '#a0a0a0'
    - '#5fd080'
    - '#1b1b1b'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
