layout_spectrum: 0.2594
favicon: null
name: Filippo Teodoro
purpose: []
analytics:
  twitter: null
  google: UA-62290697-4
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5042553
  lightness: 0.7234042
  saturation: 0.5234042
  rhythmicContrast: 0.4893617
  brandColors:
    - '#060606'
    - '#5F83BD'
    - '#FFFFFF'
    - '#213D59'
    - '#BBBDC8'
typography_spectrum: 0.49875
