name: Filippo Teodoro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62290697-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
